name: Transfer README
on: 
  push:
    branches: [ main ]
    paths: [ "README.md" ] 
  workflow_dispatch:

jobs:
  transfer-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Execute Transfer ğŸš€
        uses: GuillaumeFalourd/copy-push-files@test
        with:
          source_files: README.md
          remote_repository: https://github.com/lifecharities/.github
          commit_message: Update README
          target_dir: profile
          target_branch: main
          access_token: ${{ secrets.ACCESS_TOKEN }}
